"""
test_challenger_m1_gate2_concurrency.py
Deep Empirical Concurrency & Stress Verification Test Suite for Milestone 1 Gate 2.
Author: challenger_m1_gate2_1 (Empirical Challenger)

Specifically challenges:
1. add_activity_log under high concurrent load: 50 threads x 30 writes (1500 writes) barrier blast.
   Verifies: Zero primary key collisions, entropy format compliance, exact count match.
2. POST /api/accounts under high concurrent load: 30-50 threads competing for the exact same targetId.
   Verifies: Zero 500 errors, zero UNIQUE constraint failures, atomic upsert, ID preservation.
3. Mixed multi-target concurrent upserts with concurrent readers:
   Verifies: Zero lockups, WAL read/write concurrency, data consistency.
4. Concurrent upserts with competing custom IDs:
   Verifies: Primary key immutability and conflict resolution.
5. Concurrent upsert + health state transition contention:
   Verifies: Absence of deadlocks between accounts router endpoints.
"""

import os
import sys
import time
import re
import uuid
import threading
from typing import List, Dict, Any
import pytest
from fastapi.testclient import TestClient

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

from app.main import app
from app.core.config import settings
from app.db.session import (
    get_connection,
    get_db,
    transaction,
    query_all,
    query_one,
    execute_write,
    close_thread_connection,
    add_activity_log,
)

client = TestClient(app)

class TestMilestone1Gate2ConcurrencyVerification:
    """Rigorous empirical verification of Milestone 1 concurrency defect resolutions."""

    # --------------------------------------------------------------------------
    # REQUIREMENT 2: add_activity_log Stress Verification
    # --------------------------------------------------------------------------

    def test_add_activity_log_massive_concurrency_blast(self):
        """
        Adversarial Challenge: 50 concurrent threads simultaneously blasting add_activity_log.
        Each thread executes 30 rapid log operations (1500 total operations) without delay.
        Validates:
        1. Zero primary key collisions (sqlite3.IntegrityError: UNIQUE constraint failed: logs.id)
        2. Zero lock timeouts (OperationalError: database is locked)
        3. All generated log IDs are unique (100% distinct set)
        4. Every log ID adheres to the format 'log_{now_ms}_{entropy}' where entropy is 6 hex chars
        5. Database record count matches exactly 1500 rows
        """
        num_threads = 50
        writes_per_thread = 30
        total_expected_logs = num_threads * writes_per_thread
        barrier = threading.Barrier(num_threads)

        errors: List[Exception] = []
        captured_ids: List[str] = []
        lock = threading.Lock()

        test_tag = f"gate2_blast_{int(time.time() * 1000)}_{uuid.uuid4().hex[:4]}"

        def worker(thread_idx: int):
            try:
                barrier.wait(timeout=10.0)
                local_ids = []
                for i in range(writes_per_thread):
                    log_id = add_activity_log(
                        action="CHALLENGER_GATE2_STRESS",
                        entity_type="thread_worker",
                        entity_id=f"t_{thread_idx}_seq_{i}",
                        project_key="all",
                        details={"tag": test_tag, "thread": thread_idx, "iteration": i}
                    )
                    local_ids.append(log_id)
                with lock:
                    captured_ids.extend(local_ids)
            except Exception as e:
                with lock:
                    errors.append(e)
            finally:
                close_thread_connection()

        threads = [threading.Thread(target=worker, args=(i,)) for i in range(num_threads)]
        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=30.0)

        # Query database for rows created during this test
        db_rows = query_all(
            "SELECT id, details FROM logs WHERE action = 'CHALLENGER_GATE2_STRESS' AND details LIKE ?",
            (f"%{test_tag}%",)
        )

        # Cleanup test data immediately
        execute_write(
            "DELETE FROM logs WHERE action = 'CHALLENGER_GATE2_STRESS' AND details LIKE ?",
            (f"%{test_tag}%",)
        )

        # 1. Check no worker raised an exception
        assert len(errors) == 0, f"add_activity_log crashed under 50-thread contention: {errors}"

        # 2. Check total logs generated by workers
        assert len(captured_ids) == total_expected_logs, (
            f"Expected {total_expected_logs} log IDs, but captured {len(captured_ids)}"
        )

        # 3. Check for zero duplicates in returned IDs
        unique_ids = set(captured_ids)
        assert len(unique_ids) == total_expected_logs, (
            f"Primary key collision detected! {total_expected_logs - len(unique_ids)} duplicate IDs found!"
        )

        # 4. Check ID structure matches regex: log_<timestamp>_<6 hex chars>
        log_pattern = re.compile(r"^log_\d+_[0-9a-f]{6}$")
        invalid_format_ids = [lid for lid in captured_ids if not log_pattern.match(lid)]
        assert len(invalid_format_ids) == 0, (
            f"Found IDs that do not follow log_<timestamp>_<entropy> format: {invalid_format_ids[:5]}"
        )

        # 5. Check database actually saved every single row
        assert len(db_rows) == total_expected_logs, (
            f"Database row count mismatch: Expected {total_expected_logs}, found {len(db_rows)} in sqlite table"
        )

    # --------------------------------------------------------------------------
    # REQUIREMENT 3: POST /api/accounts Concurrent Upsert Stress Verification
    # --------------------------------------------------------------------------

    def test_post_accounts_single_target_high_concurrency_upsert(self):
        """
        Adversarial Challenge: 30 concurrent threads simultaneously POST /api/accounts
        with the EXACT same targetId, each attempting to write differing tokens and names.
        Validates:
        1. Zero 500 Internal Server Errors (No unhandled sqlite3.IntegrityError: UNIQUE constraint failed: accounts.target_id)
        2. Every request returns HTTP 200 with success=True
        3. Exactly ONE record exists in the database for that targetId
        4. The record's original primary key (id) and created_at remain stable (immutability under upsert)
        5. The final record has updated dynamic values and updated_at >= created_at
        """
        thread_count = 30
        barrier = threading.Barrier(thread_count)
        shared_target_id = f"target_fb_{int(time.time() * 1000)}_{uuid.uuid4().hex[:4]}"

        # Seed valid workers in the database so foreign key constraints are satisfied
        for wid in ["worker_0", "worker_1", "worker_2"]:
            execute_write(
                "INSERT INTO workers (id, name, status, last_heartbeat, created_at, updated_at) "
                "VALUES (?, ?, 'idle', ?, ?, ?) ON CONFLICT(id) DO NOTHING",
                (wid, f"Test Node {wid}", int(time.time() * 1000), int(time.time() * 1000), int(time.time() * 1000))
            )

        status_codes: List[int] = []
        response_bodies: List[Dict[str, Any]] = []
        errors: List[Exception] = []
        lock = threading.Lock()

        def worker(thread_idx: int):
            try:
                barrier.wait(timeout=10.0)
                payload = {
                    "name": f"Account Version {thread_idx}",
                    "accessToken": f"EAAB_token_worker_{thread_idx}",
                    "targetId": shared_target_id,
                    "type": "profile",
                    "projectKey": "all",
                    "workerId": f"worker_{thread_idx % 3}"
                }
                res = client.post("/api/accounts", json=payload)
                with lock:
                    status_codes.append(res.status_code)
                    if res.headers.get("content-type", "").startswith("application/json"):
                        response_bodies.append(res.json())
                    else:
                        response_bodies.append({"raw": res.text})
            except Exception as e:
                with lock:
                    errors.append(e)

        threads = [threading.Thread(target=worker, args=(i,)) for i in range(thread_count)]
        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=20.0)

        # Query database state
        saved_accounts = query_all("SELECT * FROM accounts WHERE target_id = ?", (shared_target_id,))

        # Cleanup
        execute_write("DELETE FROM accounts WHERE target_id = ?", (shared_target_id,))
        execute_write("DELETE FROM logs WHERE entity_id IN (SELECT id FROM accounts WHERE target_id = ?)", (shared_target_id,))
        execute_write("DELETE FROM workers WHERE id IN ('worker_0', 'worker_1', 'worker_2')")

        # 1. Zero exceptions raised
        assert len(errors) == 0, f"Worker threads encountered unexpected client exceptions: {errors}"

        # 2. Check all status codes are 200 or 201
        non_success = [code for code in status_codes if code not in [200, 201]]
        assert len(non_success) == 0, (
            f"Detected non-success responses under concurrent upsert: {non_success}. "
            f"Sample responses: {response_bodies[:3]}"
        )

        # 3. Check every response body indicated success
        failed_bodies = [b for b in response_bodies if not b.get("success")]
        assert len(failed_bodies) == 0, f"Responses failed: {failed_bodies}"

        # 4. Exactly 1 record must exist in the database (no duplicate rows inserted)
        assert len(saved_accounts) == 1, (
            f"Expected exactly 1 account record for targetId {shared_target_id}, but found {len(saved_accounts)}"
        )

        record = saved_accounts[0]
        # 5. Check integrity of stored account fields
        assert record["target_id"] == shared_target_id
        assert record["status"] == "active"
        assert record["cookie_status"] == "valid"
        assert record["updated_at"] >= record["created_at"]
        assert record["name"].startswith("Account Version")
        assert record["access_token"].startswith("EAAB_token_worker_")

    def test_post_accounts_multi_target_mixed_concurrent_upsert(self):
        """
        Adversarial Challenge: 40 threads partitioned across 4 distinct target IDs
        (10 threads per target ID) all firing simultaneously.
        Verifies:
        1. All 4 targets survive high-load contention without lockups or 500s.
        2. Exactly 4 rows exist in the database (one per target ID).
        3. No cross-talk or data contamination between targets.
        """
        targets = [f"multi_target_{i}_{int(time.time() * 1000)}" for i in range(4)]
        threads_per_target = 10
        total_threads = len(targets) * threads_per_target
        barrier = threading.Barrier(total_threads)

        status_codes = []
        errors = []
        lock = threading.Lock()

        def worker(target_id: str, idx: int):
            try:
                barrier.wait(timeout=10.0)
                payload = {
                    "name": f"User {target_id}_{idx}",
                    "accessToken": f"token_{target_id}_{idx}",
                    "targetId": target_id,
                    "type": "page"
                }
                res = client.post("/api/accounts", json=payload)
                with lock:
                    status_codes.append(res.status_code)
            except Exception as e:
                with lock:
                    errors.append(e)

        threads = []
        for target_id in targets:
            for idx in range(threads_per_target):
                threads.append(threading.Thread(target=worker, args=(target_id, idx)))

        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=25.0)

        # Query database counts
        db_rows = query_all("SELECT * FROM accounts WHERE target_id IN (?, ?, ?, ?)", tuple(targets))

        # Cleanup
        for target_id in targets:
            execute_write("DELETE FROM accounts WHERE target_id = ?", (target_id,))

        assert len(errors) == 0, f"Exceptions occurred: {errors}"
        assert all(code in [200, 201] for code in status_codes), f"Status code failures: {status_codes}"
        assert len(db_rows) == 4, f"Expected 4 distinct account rows, got {len(db_rows)}"

        retrieved_targets = {row["target_id"] for row in db_rows}
        assert retrieved_targets == set(targets), f"Missing target IDs: {set(targets) - retrieved_targets}"

    def test_post_accounts_competing_custom_ids_preserves_initial_id(self):
        """
        Adversarial Challenge: Concurrent upsert where caller provides custom IDs.
        Thread A specifies id='custom_acc_A', Thread B specifies id='custom_acc_B',
        both specifying the same targetId.
        Verifies:
        1. Atomic ON CONFLICT(target_id) DO UPDATE SET preserves the first committed 'id'.
        2. No secondary UNIQUE constraint crashes on the primary key 'id'.
        """
        thread_count = 15
        barrier = threading.Barrier(thread_count)
        shared_target = f"custom_id_target_{int(time.time() * 1000)}"

        status_codes = []
        returned_account_ids = []
        lock = threading.Lock()

        def worker(idx: int):
            try:
                barrier.wait(timeout=5.0)
                payload = {
                    "id": f"acc_custom_{shared_target}_{idx}",
                    "name": f"Custom ID Acc {idx}",
                    "accessToken": f"tok_{idx}",
                    "targetId": shared_target,
                    "type": "profile"
                }
                res = client.post("/api/accounts", json=payload)
                with lock:
                    status_codes.append(res.status_code)
                    if res.status_code in [200, 201]:
                        body = res.json()
                        returned_account_ids.append(body.get("account", {}).get("id"))
            except Exception as e:
                with lock:
                    status_codes.append(-1)

        threads = [threading.Thread(target=worker, args=(i,)) for i in range(thread_count)]
        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=15.0)

        # Check DB
        db_accounts = query_all("SELECT * FROM accounts WHERE target_id = ?", (shared_target,))

        # Cleanup
        execute_write("DELETE FROM accounts WHERE target_id = ?", (shared_target,))

        assert all(code in [200, 201] for code in status_codes), f"Status failures: {status_codes}"
        assert len(db_accounts) == 1, f"Expected 1 record, got {len(db_accounts)}"

        committed_id = db_accounts[0]["id"]
        # All returned accounts after the first upsert must refer to the persistent committed ID
        assert committed_id in returned_account_ids

    def test_concurrent_account_upsert_and_health_transition(self):
        """
        Adversarial Challenge: Interleaved execution of POST /api/accounts (upsert)
        and POST /api/accounts/{account_id}/health (status update) across 20 threads.
        Verifies:
        1. No deadlocks between accounts router endpoints.
        2. Account status updates cleanly transition without database lock errors.
        """
        account_target = f"health_stress_{int(time.time() * 1000)}"
        
        # Seed the account first
        seed_res = client.post("/api/accounts", json={
            "name": "Health Test Account",
            "accessToken": "seed_token",
            "targetId": account_target,
            "type": "page"
        })
        assert seed_res.status_code in [200, 201]
        account_id = seed_res.json()["account"]["id"]

        thread_count = 20
        barrier = threading.Barrier(thread_count)
        statuses = ["healthy", "checkpoint", "logged_out", "expired"]
        results = []
        lock = threading.Lock()

        def worker(idx: int):
            try:
                barrier.wait(timeout=5.0)
                if idx % 2 == 0:
                    # Upsert worker
                    res = client.post("/api/accounts", json={
                        "name": f"Interleaved Name {idx}",
                        "accessToken": f"token_int_{idx}",
                        "targetId": account_target,
                        "type": "page"
                    })
                    with lock:
                        results.append(("upsert", res.status_code))
                else:
                    # Health worker
                    chosen_status = statuses[idx % len(statuses)]
                    res = client.post(f"/api/accounts/{account_id}/health", json={
                        "healthStatus": chosen_status
                    })
                    with lock:
                        results.append(("health", res.status_code))
            except Exception as e:
                with lock:
                    results.append(("error", str(e)))

        threads = [threading.Thread(target=worker, args=(i,)) for i in range(thread_count)]
        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=15.0)

        # Cleanup
        execute_write("DELETE FROM accounts WHERE target_id = ?", (account_target,))
        execute_write("DELETE FROM logs WHERE entity_id = ?", (account_id,))

        # Verify all operations succeeded with HTTP 200 or 201
        failed_ops = [r for r in results if r[1] not in [200, 201]]
        assert len(failed_ops) == 0, f"Interleaved operations had failures: {failed_ops}"

    def test_add_activity_log_100_threads_saturation(self):
        """
        Adversarial Challenge: 100 concurrent threads executing 20 writes each (2000 total writes).
        Tests whether the 6-hex-char entropy space (16,777,216 values per ms) ever experiences
        a birthday attack collision under heavy thread saturation.
        """
        num_threads = 100
        writes_per_thread = 20
        total_expected = num_threads * writes_per_thread
        barrier = threading.Barrier(num_threads)

        errors = []
        captured_ids = []
        lock = threading.Lock()
        tag = f"sat_{int(time.time() * 1000)}_{uuid.uuid4().hex[:4]}"

        def worker(thread_idx: int):
            try:
                barrier.wait(timeout=10.0)
                local = []
                for i in range(writes_per_thread):
                    lid = add_activity_log("SATURATION_STRESS", "sat_worker", f"w_{thread_idx}_{i}", details={"tag": tag})
                    local.append(lid)
                with lock:
                    captured_ids.extend(local)
            except Exception as e:
                with lock:
                    errors.append(e)
            finally:
                close_thread_connection()

        threads = [threading.Thread(target=worker, args=(i,)) for i in range(num_threads)]
        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=30.0)

        # Count in db
        saved_count = query_one(
            "SELECT count(*) as cnt FROM logs WHERE action = 'SATURATION_STRESS' AND details LIKE ?",
            (f"%{tag}%",)
        )["cnt"]

        # Cleanup
        execute_write("DELETE FROM logs WHERE action = 'SATURATION_STRESS' AND details LIKE ?", (f"%{tag}%",))

        assert len(errors) == 0, f"Errors under 100-thread saturation: {errors}"
        assert len(captured_ids) == total_expected, f"Captured {len(captured_ids)} vs expected {total_expected}"
        assert len(set(captured_ids)) == total_expected, (
            f"PK collision under 100-thread saturation! Duplicates: {total_expected - len(set(captured_ids))}"
        )
        assert saved_count == total_expected, f"DB saved {saved_count} rows vs expected {total_expected}"

    def test_post_accounts_extreme_contention_100_threads(self):
        """
        Adversarial Challenge: 100 concurrent threads blasting POST /api/accounts for the EXACT SAME targetId.
        Tests SQLite ON CONFLICT(target_id) DO UPDATE SET under extreme write lock contention.
        Verifies:
        1. Zero crashes (no UNIQUE constraint failed, no SQLITE_BUSY, no 500s).
        2. Exactly 1 row in the database.
        3. All 100 requests return HTTP 201.
        4. Account ID remains immutable.
        """
        thread_count = 100
        barrier = threading.Barrier(thread_count)
        shared_target = f"extreme_target_{int(time.time() * 1000)}_{uuid.uuid4().hex[:4]}"

        status_codes = []
        errors = []
        account_ids = []
        lock = threading.Lock()

        def worker(thread_idx: int):
            try:
                barrier.wait(timeout=10.0)
                payload = {
                    "name": f"Extreme Name {thread_idx}",
                    "accessToken": f"tok_{thread_idx}",
                    "targetId": shared_target,
                    "type": "profile"
                }
                res = client.post("/api/accounts", json=payload)
                with lock:
                    status_codes.append(res.status_code)
                    if res.status_code in [200, 201]:
                        account_ids.append(res.json().get("account", {}).get("id"))
            except Exception as e:
                with lock:
                    errors.append(e)

        threads = [threading.Thread(target=worker, args=(i,)) for i in range(thread_count)]
        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=30.0)

        # DB check
        rows = query_all("SELECT * FROM accounts WHERE target_id = ?", (shared_target,))

        # Cleanup
        execute_write("DELETE FROM accounts WHERE target_id = ?", (shared_target,))
        execute_write("DELETE FROM logs WHERE entity_id IN (SELECT id FROM accounts WHERE target_id = ?)", (shared_target,))

        assert len(errors) == 0, f"Worker exceptions: {errors}"
        assert all(code in [200, 201] for code in status_codes), f"Status code failures: {set(status_codes)}"
        assert len(rows) == 1, f"Expected 1 record, found {len(rows)}"
        assert len(set(account_ids)) == 1, f"Account ID mutated during upsert! Found IDs: {set(account_ids)}"

